source ENV['GEM_SOURCE'] || "https://rubygems.org"

#gem "em-jsonrpc", :require => false
#gem "eventmachine", :require => false

# Evaluate Gemfile.local if it exists
if File.exists? "#{__FILE__}.local"
  eval(File.read("#{__FILE__}.local"), binding)
end

# Evaluate ~/.gemfile if it exists
if File.exists?(File.join(Dir.home, '.gemfile'))
  eval(File.read(File.join(Dir.home, '.gemfile')), binding)
end
